version: '3'

services:
  pokedexapp:
    # depends_on:
    #   - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '80:3000'
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: 3000
      DEFAULT_LIMIT: 5
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
